In [1]:
import os
import cv2
import numpy as np
import random
from PIL import Image
import json

In [2]:
fg = cv2.imread("test/src/COCO_train2014_000000001510.png",-1)
bg = cv2.imread("test/dst/bing_bg_1_0105.jpg")
ins = cv2.imread("test/ins/COCO_train2014_000000000853.png",-1)
gt = cv2.imread("test/gt/COCO_train2014_000000000450_test.png",-1)

In [31]:
arr = np.random.randint(0,10, (3,4))  
index = np.argwhere(arr < 5)

index1 = np.argwhere(ins == 255)
#print(ins[index1])
print(index1[0])
print(ins[index1[0]][index1[1]][index1[2]])

[  0 254   1]


IndexError: index 255 is out of bounds for axis 0 with size 3

In [38]:
if ins.any()==255:
    print("yes") 
else:
    print('no')

#alpha_full = np.zeros(backg.shape, dtype=backg.dtype)
#ins_full = alpha_full.copy()
#alpha_full[0:100,0:100] += backg[0:100,0:100]

print(ins.shape)
b,g,r = cv2.split(ins)
z = np.zeros(b.shape, dtype=b.dtype)
#print(r[300])
b_new_1 = cv2.merge((b,z,z))
b_new_2 = cv2.merge((b,b,b))

#cv2.imwrite("blue_2.png",b_new_2)

#======================================================
np_arr = np.array([[0 ,0, 1, 1],[1,0,1,1]])
#print(np_arr)
#print(np.int64(np_arr==255))
#==========================================================

b_new_imp = np.uint8(b_new_1==255)
print(b_new_1[400][500])
print(b_new_1[0][0])
print(b_new_imp[0][0])

print(type(ins[0][0]))
print(type(b_new_imp[0][0][0]))

cv2.imwrite("blue_imp.png",b_new_imp)

(480, 640, 3)
[255   0   0]
[1 0 0]
[0 0 0]
<class 'numpy.ndarray'>
<class 'numpy.uint8'>


True

In [102]:
info = {
    "name":"hjc",
    "age":22
}
alist = [1,2,3,4]
dic = {
"COCO_conver": [
		{ "name":alist , "url":"COCO" }, 
		{ "name":"sport" , "url":"COCO" }, 
		{ "name":"tv" , "url":"COCO_1" }
	]
}
dic["COCO_conver"].append({"background":"cc"})
dic.update({"yes":"test"})
with open("a1.txt","w",encoding="utf-8") as f:
    f.write(json.dumps(dic))
for i in dic:
    print(dic[i])

[{'name': [1, 2, 3, 4], 'url': 'COCO'}, {'name': 'sport', 'url': 'COCO'}, {'name': 'tv', 'url': 'COCO_1'}, {'background': 'cc'}]
test


In [79]:
with open("a1.txt","r",encoding="utf-8") as f:
    data = json.loads(f.readline())
    print(data["COCO_conver"][0]["name"])

[1, 2, 3, 4]


In [66]:
print(gt.shape)
def judge(pix):
    if pix[0] > 0 or pix[1] > 0 or pix[2] > 0:
        return 1
    else:
        return 0

n = gt[0:5,0:5].copy()
n[1][1][1] = 2

print(get_area(n))

(389, 600, 3)
1
25
0.04


In [96]:
a = '1:abcdefg'
print(a[2:])

abcdefg


In [15]:
def replace_color(img, src_clr, dst_clr):
    img_arr = np.asarray(img, dtype=np.double)   
    #分离通道
    r_img = img_arr[:,:,0].copy()
    g_img = img_arr[:,:,1].copy()
    b_img = img_arr[:,:,2].copy()

	#编码
    img = r_img * 256 * 256 + g_img * 256 + b_img
    src_color = src_clr[0] * 256 * 256 + src_clr[1] * 256 + src_clr[2]
    
    #索引并替换颜色
    r_img[img == src_color] = dst_clr[0]
    g_img[img == src_color] = dst_clr[1]
    b_img[img == src_color] = dst_clr[2]
    
    #合并通道
    dst_img = np.array([r_img, g_img, b_img], dtype=np.uint8)
    #将数据转换为图像数据(h,w,c)
    dst_img = dst_img.transpose(1,2,0) 
    return dst_img

In [20]:
img = Image.open("blue.png").convert('RGB')
dst_img = replace_color(img, (255,0,0), (0,0,255))

res_img = dst_img
res_img = Image.fromarray(res_img)
res_img.save("blue_trans.png")

In [25]:
np_arr = np.array([[0 ,0, 1, 1],[1,0,1,1]])
print(np_arr)
print(np.int64(np_arr==255))

[[0 0 1 1]
 [1 0 1 1]]
[[0 0 0 0]
 [0 0 0 0]]
